[package]
name = "flip_coin"
version = "0.0.1"
authors = ["Israel Croce <israelcroce@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"